---
name: Run E2E Test
description: Run E2E Test

inputs:
  codebase-artifact:
    description: Codebase Artifact to Download
    required: true

runs:
  using: composite
  steps:
    - name: Download Necessary Artifacts
      shell: bash
      run: |
        # setup kind
        if [ -z $(which kind) ]; then
          echo "kind executable not found...installing"
          curl https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 -o /usr/local/bin/kind -L
          chmod +x /usr/local/bin/kind
        else
          echo "found kind executable at $(which kind)...not installing"
        fi

        # setup kubectl
        if [ -z $(which kubectl) ]; then
          curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl
        else
          echo "found kubectl executable at $(which kubectl)...not installing"
        fi
      env:
        KIND_VERSION: v0.10.0
        KUBECTL_VERSION: v1.20.0

    - name: Setup KIND Cluster
      shell: bash
      run: kind create cluster --name operator-builder-test

    - name: Run E2E Tests
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: |
        # ensure the kustomize/controller-gen binaries are downloaded
        # and executable
        make controller-gen && make kustomize
        chmod +x bin/controller-gen && chmod +x bin/kustomize

        # TODO: this is temporary to ensure we test the reconciliation loop
        # for our test workloads.  the end goal would be to genericize this
        # to ensure we can test any workload.
        if [[ -f .workloadConfig/v1alpha1_workloads_test.go.test ]]; then
          cp .workloadConfig/v1alpha1_workloads_test.go.test test/e2e/v1alpha1_workloads_test.go
        fi

        # run the e2e tests
        make test-e2e
      env:
        IMG: localhost:5000/${{ inputs.codebase-artifact }}:latest
        USE_CONTROLLER: "true"
        DEPLOY: "true"
        TEARDOWN: "true"

    # TODO: this is a stub until this action is fixed.  currently, the make
    # targets are inconsistently missing.
    # - name: Install Documentation
    #   shell: bash
    #   working-directory: /tmp/operator-builder-test
    #   run: make docs
