---
name: Build
on:
  - pull_request
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Binary Artifact (operator-builder)
        run: make build

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: operator-builder
          path: bin/operator-builder
