---
name: Release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # TODO: readdress this task as it prevented a successful release
      # See action https://github.com/vmware-tanzu-labs/operator-builder/runs/4861431396?check_suite_focus=true
      # - name: Set up Snapcraft
      #   # FIXME: the mkdirs are a hack for https://github.com/goreleaser/goreleaser/issues/1715
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
      #     mkdir -p $HOME/.cache/snapcraft/download
      #     mkdir -p $HOME/.cache/snapcraft/stage-packages

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: readdress this task as it prevented a successful release
      # See action https://github.com/vmware-tanzu-labs/operator-builder/runs/4861431396?check_suite_focus=true
      # - name: Snapcraft Login
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: |
      #     snapcraft login --with <(echo "${{ secrets.SNAPCRAFT_LOGIN }}")

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist -f  ./.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
