---
name: Test
on:
  - pull_request
  - push

jobs:
  #
  # unit testing
  #
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run Test
        uses: ./.github/common-actions/unit-test

  #
  # build and store artifact
  #
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Binary Artifact (operator-builder)
        run: make build

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: operator-builder
          path: bin/operator-builder

  #
  # functional test
  #
  functional-test:
    name: Functional Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Standalone Operator
            artifact: standalone-codebase
            test-workload-path: test/cases/application
          - name: Standalone Edge Cases Operator
            artifact: standalone-edge-codebase
            test-workload-path: test/cases/edge-standalone
          - name: Workload Collection Operator
            artifact: collection-codebase
            test-workload-path: test/cases/platform
          - name: Workload Collection Edge Cases Operator
            artifact: collection-edge-codebase
            test-workload-path: test/cases/edge-collection
    env:
      TEST_WORKLOAD_PATH: "${{ matrix.test-workload-path }}"
      TEST_PATH: "/tmp/operator-builder-func-test"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download operator-builder Binary
        uses: actions/download-artifact@v2
        with:
          name: operator-builder
          path: bin

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Initialize ${{ matrix.name }} Codebase
        run: |
          chmod +x bin/operator-builder
          make func-test-clean
          make func-test-init

      - name: Create ${{ matrix.name }} Codebase
        run: make func-test-create

      - name: Store ${{ matrix.name }} Codebase
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: ${{ env.TEST_PATH }}

  #
  # e2e test
  #
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    needs: functional-test
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        include:
          # NOTE: at this time we should only test the standalone CLI as the
          # inputs to the collection CLI become much more complicated to test.
          - name: Standalone Operator
            artifact: standalone-codebase
            test-build: "true"
            test-deploy: "true"
          - name: Standalone Edge Cases Operator
            artifact: standalone-edge-codebase
            test-build: "false"
            test-deploy: "false"
          - name: Workload Collection Operator
            artifact: collection-codebase
            test-build: "true"
            test-deploy: "false"
          - name: Workload Collection Edge Cases Operator
            artifact: collection-edge-codebase
            test-build: "true"
            test-deploy: "false"
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    defaults:
      run:
        working-directory: /tmp/operator-builder-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download ${{ matrix.name }} Codebase
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: /tmp/operator-builder-test

      - name: Run E2E Tests
        uses: ./.github/common-actions/e2e-test
        with:
          codebase-artifact: ${{ matrix.artifact }}

      - name: Run CLI Integration Tests
        uses: ./.github/common-actions/e2e-test-cli
        with:
          test-build: ${{ matrix.test-build }}
          test-deploy: ${{ matrix.test-deploy }}
